service:
  ui:
    type: LoadBalancer  # 기존 그대로 유지

defaultSettings:
  # 복제본 수. 소규모/저부하 권장값 2 (노드 하나 죽어도 복구용).
  # 진짜 경량/단일노드면 1로 낮출 수 있지만 장애 내성 사라짐.
  defaultReplicaCount: 2

  # 소수 노드에서 스케줄링 유연성↑
  replicaSoftAntiAffinity: true

  # 엔진 고정 CPU 안 잡음(작은 클러스터에 유리)
  guaranteedEngineCPU: 0

  # 용량 관련(보수적으로)
  storageOverProvisioningPercentage: 100
  storageMinimalAvailablePercentage: 5

  # 불필요한 원격 체크/통계 끄기
  upgradeChecker: false
  allowCollectingLonghornUsageMetrics: false

  # 잡 스냅샷/고아 볼륨 자동 정리
  orphanAutoDeletion: true
  autoCleanupSystemGeneratedSnapshot: true

  # 기본 디스크/SC 생성 편의
  createDefaultDiskLabeledNodes: true
  defaultLonghornStaticStorageClass: longhorn

ingress:
  enabled: false

metrics:
  serviceMonitor:
    enabled: false

